apiVersion: v1
kind: Service
metadata:
  name: exporter-calico
  namespace: kube-system
  labels:
    app: exporter-calico
    component: calico-node
    chart: {{ template "kubernetes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.calicoExporterPort }}
      targetPort: {{ .Values.calicoExporterPort }}
      protocol: TCP
  selector:
    k8s-app: calico-node